[package]
name = "gadgets"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.68"
plonky2 = { git = "https://github.com/benjaminbollen/plonky2", branch = "20221229-snapshot-main"}
